### ISSUE TITLE
Request for large tenants: Handle API throttling limits

### ISSUE THREAD

**Issue by FrankPreusker** [GT-Analytics/fuam-basic#7]
We do need to include Personal Workspaces into the metadata scanning (easy to adjust in the notebook), but this is catapulting us beyond the 500 requests per hour limit of the Scanner API (>50k workspaces). So the solution has to be able to deal with throttling limits (equally true for other API calls as well).

**Comment by ggintli** [comment]
Dear Frank,

This feature is not is scope of the FUAM Basic package. 
There is a great solution for one time analysis of personal workspaces: https://github.com/microsoft/Fabric-metadata-scanning

I hope it helps.
Best Regards,

**Comment by ggintli** [comment]
Dear Frank,

This feature is not is scope of the FUAM Basic package. 
There is a great solution for one time analysis of personal workspaces: https://github.com/microsoft/Fabric-metadata-scanning

I hope it helps.
Best Regards
